### ISSUE TITLE
can this function run in kinetic version?

### ISSUE THREAD

**Issue by juda** [Jrdevil-Wang/shm_transport#3]
Hi Wang,
    I attempt to run your shm_transport code in kinetic version but always fail during compile because of SteadyTime file.
   Did you try to run your code in other version? 

Thx

**Comment by juda** [comment]
Even in lunar environment, I also got:

/home/ju/automobile/ros_lunar/src/ros_comm/test/test_shm_transport/test/shm_talker.cpp:2:29: fatal error: ros/shm_topic.hpp: No such file or directory
compilation terminated.
/home/ju/automobile/ros_lunar/src/ros_comm/test/test_shm_transport/test/shm_listener.cpp:2:29: fatal error: ros/shm_topic.hpp: No such file or directory
compilation terminated.
CMakeFiles/shm_talker.dir/build.make:62: recipe for target 'CMakeFiles/shm_talker.dir/test/shm_talker.cpp.o' failed
make[2]: *** [CMakeFiles/shm_talker.dir/test/shm_talker.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/shm_talker.dir/all' failed
make[1]: *** [CMakeFiles/shm_talker.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/shm_listener.dir/build.make:62: recipe for target 'CMakeFiles/shm_listener.dir/test/shm_listener.cpp.o' failed
make[2]: *** [CMakeFiles/shm_listener.dir/test/shm_listener.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/shm_listener.dir/all' failed
make[1]: *** [CMakeFiles/shm_listener.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2


I use your ros_comm version and haven't change any files, but also got error. That makes me fell strange because I found you submit a PR to ros_comm and it builds successfully.

**Comment by twd2** [comment]
I *think* it can, but some work may be done.

Our project uses Ubuntu 14.04 so we didn't try to run this code in other version.

**Comment by juda** [comment]
Thank you for reply.
I fixed some conflicts, so it's runnable under other ubuntu version.
However, I face another problem.
I think 2nd floor is another issue, that is, I cannot compile the shm because compiler cannot find shm_*.hpp
Could you give me some details that how do you guys build the new codes?

**Comment by juda** [comment]
From the last comment at https://github.com/ros/ros_comm/issues/1082
It seems that the your tests still have some problems? I got the bug info above from test program.

**Comment by Jrdevil-Wang** [comment]
I tested the code on indigo, and I think it can run under other versions too.
But my tests are based on ros_comm-1.13.0 when there are no SteadyTime files, because the lated lunar version can not compile on my environment. I got errors like:

In file included from /home/jrdevil/Documents/ros_ws/devel/include/ros/common.h:37:0,
                 from /home/jrdevil/Documents/ros_ws/src/ros_comm/clients/roscpp/src/libros/common.cpp:35:
/home/jrdevil/Documents/ros_ws/src/ros_comm/clients/roscpp/include/ros/forwards.h:169:3: error: ‘SteadyTime’ does not name a type
   SteadyTime last_expected;            ///< In a perfect world, this is when the last callback should have happened
   ^

**Comment by Jrdevil-Wang** [comment]
Thanks for your attention. @juda 
I am trying to merge this project into ros_comm project, but there are still problems on tests.
Other than that, this project can be run as a normal ros application.

**Comment by juda** [comment]
@Jrdevil-Wang 
I also attempt to merge your work into ros_comm(lunar branch), but always failed.
By the way, I haven't run it as normal ros application yet, but I think it's a good way to test your code.

Thank you for you guys' work, it's an appreciated way to implement shared memory.

**Comment by juda** [comment]
I try to run shm_transport as a normal ros application but face new dilemma.
I build all package successfully, but when I type "rosrun shm_transport shm_talker", I got 
"[rosrun] Couldn't find executable named shm_talker below /home/ju/automobile/ros_shm/install_isolated/share/shm_transport"

No idea about it. Under both kinetic and indigo this problem occurs.

**Comment by juda** [comment]
It works when I build code from apt-get.
It would fail when following http://wiki.ros.org/kinetic/Installation/Source

**Comment by twd2** [comment]
Thanks for these information.

**Comment by juda** [comment]
By the way, I don't think ROS community would merge your PR, because you guys change the API/behavior a bit. It's just an application.
A better approach is adding a switch and changing code at Topic_manager so for user the transportation is a black box.

**Comment by Jrdevil-Wang** [comment]
Thanks for the advice. @juda 
It is a little difficult since advertise a topic using shared memory need a "memory_size" parameter, which forces us to change the API a little.
But in my opinion, what we are trying to do in the PR is just like what image_transport have done.
Or if I should commit as an independent software package?

**Comment by juda** [comment]
@Jrdevil-Wang it's reasonable committing it as an independent package.
Hope your PR will be accepted ASAP.
